version: 2.1

orbs:
  architect: giantswarm/architect@9.3.1

workflows:
  test:
    jobs:
      - architect/go-test:
          context: architect
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - architect/go-build:
          context: architect
          name: go-build
          binary: mcli
          architectures: "linux/amd64,linux/arm64,darwin/amd64,darwin/arm64,windows/amd64,windows/arm64"
          filters:
            tags:
              only: /^v.*/
          requires:
            - go-test
      - architect/upload-release-assets:
          binary: mcli
          context: architect
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - go-build
